### ISSUE TITLE
clicking 'modify settings' makes cura 4 crash

### ISSUE THREAD

**Issue by gretel** [nallath/CuraOrientationPlugin#13]
```
Traceback (most recent call last):
  File "/Users/ultimaker/build/4.0/build/inst/lib/python3.5/site-packages/UM/Qt/Bindings/ExtensionModel.py", line 51, in subMenuTriggered
  File "/Users/ultimaker/build/4.0/build/inst/lib/python3.5/site-packages/UM/Extension.py", line 38, in activateMenuItem
  File "/Users/tom/Library/Application Support/cura/4.0/plugins/CuraOrientationPlugin/OrientationPlugin.py", line 53, in showPopup
    self._createPopup()
  File "/Users/tom/Library/Application Support/cura/4.0/plugins/CuraOrientationPlugin/OrientationPlugin.py", line 46, in _createPopup
    path = os.path.join(PluginRegistry.getInstance().getPluginPath("OrientationPlugin"), "SettingsPopup.qml")
  File "/Users/ultimaker/build/env/4.0/inst/lib/python3.5/posixpath.py", line 89, in join
  File "/Users/ultimaker/build/env/4.0/inst/lib/python3.5/genericpath.py", line 143, in _check_arg_types
TypeError: join() argument must be str or bytes, not 'NoneType'
```

**Comment by nallath** [comment]
Are you using the version you downloaded from the marketplace? Because I can't reproduce the issue using that version.
